-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\handmadedds\handmadedds_block.vhd
-- Created: 2018-06-25 16:18:39
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: handmadedds_block
-- Source Path: handmadedds/handmadedds
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY handmadedds_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        sin_out                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        cos_out                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END handmadedds_block;


ARCHITECTURE rtl OF handmadedds_block IS

  -- Component Declarations
  COMPONENT NCO_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          inc                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          sine                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          cosine                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : NCO_HDL_Optimized
    USE ENTITY work.NCO_HDL_Optimized(rtl);

  -- Signals
  SIGNAL Constant_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL NCO_HDL_Optimized_out1           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL NCO_HDL_Optimized_out2           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL NCO_HDL_Optimized_out3           : std_logic;

BEGIN
  u_NCO_HDL_Optimized : NCO_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              inc => std_logic_vector(Constant_out1),  -- uint32
              sine => NCO_HDL_Optimized_out1,  -- sfix16_En15
              cosine => NCO_HDL_Optimized_out2,  -- sfix16_En15
              validOut => NCO_HDL_Optimized_out3
              );

  Constant_out1 <= to_unsigned(1610612736, 32);

  sin_out <= NCO_HDL_Optimized_out1;

  cos_out <= NCO_HDL_Optimized_out2;

END rtl;

