set_property IOSTANDARD LVDS_25 [get_ports DAC_CLKP]
set_property PACKAGE_PIN D18 [get_ports DAC_CLKP]
set_property IOSTANDARD LVDS_25 [get_ports DAC_DCIP]
set_property PACKAGE_PIN B19 [get_ports DAC_DCIP]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[0]}]
set_property PACKAGE_PIN L18 [get_ports {DAC_DP[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[1]}]
set_property PACKAGE_PIN B16 [get_ports {DAC_DP[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[2]}]
set_property PACKAGE_PIN C17 [get_ports {DAC_DP[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[3]}]
set_property PACKAGE_PIN G19 [get_ports {DAC_DP[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[4]}]
set_property PACKAGE_PIN J20 [get_ports {DAC_DP[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[5]}]
set_property PACKAGE_PIN J21 [get_ports {DAC_DP[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[6]}]
set_property PACKAGE_PIN M19 [get_ports {DAC_DP[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[7]}]
set_property PACKAGE_PIN E15 [get_ports {DAC_DP[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[8]}]
set_property PACKAGE_PIN L17 [get_ports {DAC_DP[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[9]}]
set_property PACKAGE_PIN R20 [get_ports {DAC_DP[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[10]}]
set_property PACKAGE_PIN J18 [get_ports {DAC_DP[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[11]}]
set_property PACKAGE_PIN E21 [get_ports {DAC_DP[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[12]}]
set_property PACKAGE_PIN D20 [get_ports {DAC_DP[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[13]}]
set_property PACKAGE_PIN K19 [get_ports {DAC_DP[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[14]}]
set_property PACKAGE_PIN R19 [get_ports {DAC_DP[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DP[15]}]
set_property PACKAGE_PIN L21 [get_ports {DAC_DP[15]}]
set_property IOSTANDARD LVDS_25 [get_ports DAC_FRAMEP]
set_property PACKAGE_PIN N19 [get_ports DAC_FRAMEP]
set_property PACKAGE_PIN F18 [get_ports SPI_CLK]
set_property PACKAGE_PIN N22 [get_ports SPI_DATA]
set_property PACKAGE_PIN P22 [get_ports SPI_EN]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_DATA]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_EN]

set_property PACKAGE_PIN P20 [get_ports {TXEN[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TXEN[0]}]

set_property PACKAGE_PIN E18 [get_ports {DAC_RESET[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAC_RESET[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAC_TXEN[0]}]


set_property PACKAGE_PIN P20 [get_ports {DAC_TXEN[0]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
