# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Work/vivadoProject/ad9142/ad9142/ad9142.srcs/sources_1/bd/dac_design/ip/dac_design_ila_0_0/dac_design_ila_0_0.xci
# IP: The module: 'dac_design_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/vivadoProject/ad9142/ad9142/ad9142.srcs/sources_1/bd/dac_design/ip/dac_design_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Work/vivadoProject/ad9142/ad9142/ad9142.srcs/sources_1/bd/dac_design/ip/dac_design_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Work/vivadoProject/ad9142/ad9142/ad9142.srcs/sources_1/bd/dac_design/ip/dac_design_ila_0_0/dac_design_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Work/vivadoProject/ad9142/ad9142/ad9142.srcs/sources_1/bd/dac_design/ip/dac_design_ila_0_0/dac_design_ila_0_0.xci
# IP: The module: 'dac_design_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/vivadoProject/ad9142/ad9142/ad9142.srcs/sources_1/bd/dac_design/ip/dac_design_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Work/vivadoProject/ad9142/ad9142/ad9142.srcs/sources_1/bd/dac_design/ip/dac_design_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Work/vivadoProject/ad9142/ad9142/ad9142.srcs/sources_1/bd/dac_design/ip/dac_design_ila_0_0/dac_design_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
