# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout.xdc

# Block Designs: bd/dac_design/dac_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design || ORIG_REF_NAME==dac_design} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_processing_system7_0_0/dac_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_processing_system7_0_0 || ORIG_REF_NAME==dac_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_clk_wiz_0_0/dac_design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_clk_wiz_0_0 || ORIG_REF_NAME==dac_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_handmadedds_0_0/dac_design_handmadedds_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_handmadedds_0_0 || ORIG_REF_NAME==dac_design_handmadedds_0_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_DifferentialOutBuffer_0_0/dac_design_DifferentialOutBuffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_DifferentialOutBuffer_0_0 || ORIG_REF_NAME==dac_design_DifferentialOutBuffer_0_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_DifferentialOutBuffer_1_0/dac_design_DifferentialOutBuffer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_DifferentialOutBuffer_1_0 || ORIG_REF_NAME==dac_design_DifferentialOutBuffer_1_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_ila_0_0/dac_design_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_ila_0_0 || ORIG_REF_NAME==dac_design_ila_0_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_xlconstant_0_0/dac_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_xlconstant_0_0 || ORIG_REF_NAME==dac_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_DifferentialOutBuffer_2_0/dac_design_DifferentialOutBuffer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_DifferentialOutBuffer_2_0 || ORIG_REF_NAME==dac_design_DifferentialOutBuffer_2_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_xlconstant_1_0/dac_design_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_xlconstant_1_0 || ORIG_REF_NAME==dac_design_xlconstant_1_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_xlconstant_2_0/dac_design_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_xlconstant_2_0 || ORIG_REF_NAME==dac_design_xlconstant_2_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_axi_gpio_0_0/dac_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_axi_gpio_0_0 || ORIG_REF_NAME==dac_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_ps7_0_axi_periph_0/dac_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==dac_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_rst_ps7_0_100M_0/dac_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==dac_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_tribuffer_0_0/dac_design_tribuffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_tribuffer_0_0 || ORIG_REF_NAME==dac_design_tribuffer_0_0} -quiet] -quiet

# IP: bd/dac_design/ip/dac_design_auto_pc_0/dac_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_design_auto_pc_0 || ORIG_REF_NAME==dac_design_auto_pc_0} -quiet] -quiet

# XDC: bd/dac_design/dac_design_ooc.xdc
